# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2312d05bfd9cb6ccc80fafa0c74f72f273aeac3dcecd5edf79ef8b7b578a735a6997145b01e534ecdf809a2ab91703ef12089a90df63e4f2c7a3f8550fcac990

test:
  secret_key_base: 13bffc823080f7391e9206c51acada8e82259dd72465f852f75f7e8f96991dea522af8f8be9525d8dcdadfcc05dee6197ca34df426e821484938899c16c97f5b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
